const MAX_WORDS_LENGTH = 1500 as const

const MAX_CONTEXT_MESSAGES = 15 as const

const EXPIRED_CONVERSATION_TIME_HOURS = 3600000 as const

const MAX_HISTORY_CHAT_CARD_LENGTH = 20 as const

const CONSTANTS = {
  MAX_CONTEXT_MESSAGES,
  MAX_WORDS_LENGTH,
  EXPIRED_CONVERSATION_TIME_HOURS,
  MAX_HISTORY_CHAT_CARD_LENGTH,
}

export default CONSTANTS
